"""
PyConky Quotes Database
"""

QUOTES = [
	("There is some good in this world, and it’s worth fighting for.", "J.R.R. Tolkien", "The Two Towers"),
	("It is only with the heart that one can see rightly; what is essential is invisible to the eye.", "Antoine de Saint-Exupéry", "The Little Prince"),
	("I am no bird; and no net ensnares me: I am a free human being with an independent will, which I now exert to leave you.", "Charlotte Brontë", "Jane Eyre"),
	("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.", "Charles Dickens", "A Tale of Two Cities"),
	("Beware; for I am fearless, and therefore powerful.", "Mary Shelley", "Frankenstein"),
	("I wanted you to see what real courage is, instead of getting the idea that courage is a man with a gun in his hand. It’s when you know you’re licked before you begin but you begin anyway and you see it through no matter what. You rarely win, but sometimes you do.", "Harper Lee", "To Kill a Mockingbird"),
	("A man, after he has brushed off the dust and chips of his life, will have left only the hard, clean questions: Was it good or was it evil? Have I done well — or ill?", "John Steinbeck", "East of Eden"),
	("The only way out of the labyrinth of suffering is to forgive.", "John Green", "Looking for Alaska"),
	("This above all: To thine own self be true, And it must follow, as the night the day, Thou canst not then be false to any man.", "William Shakespeare", "Hamlet"),
	("‘Why did you do all this for me?’ he asked. ‘I don’t deserve it. I’ve never done anything for you.’ ‘You have been my friend,’ replied Charlotte. ‘That in itself is a tremendous thing.’", "E.B. White", "Charlotte’s Web"),
	("I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", "Sylvia Plath", "The Bell Jar"),
	("Love is or it ain’t. Thin love ain’t love at all.", "Toni Morrison", "Beloved"),
	("We accept the love we think we deserve.", "Stephen Chbosky", "The Perks of Being a Wallflower"),
	("And so we beat on, boats against the current, borne back ceaselessly into the past.", "F. Scott Fitzgerald", "The Great Gatsby"),
	("Generally, by the time you are Real, most of your hair has been loved off, and your eyes drop out and you get loose in the joints and very shabby. But these things don’t matter at all, because once you are Real you can’t be ugly, except to people who don’t understand.", "Margery Williams", "Velveteen Rabbit"),
	("Ever’body’s askin’ that. ‘What we comin’ to?’ Seems to me we don’t never come to nothin’. Always on the way.", "John Steinbeck", "The Grapes of Wrath"),
	("Whatever our souls are made of, his and mine are the same.", "Emily Brontë", "Wuthering Heights"),
	("There are years that ask questions and years that answer.", "Zora Neale Hurston", "Their Eyes Were Watching God"),
	("I am not afraid of storms, for I am learning how to sail my ship.", "Louisa May Alcott", "Little Women"),
	("All happy families are alike; each unhappy family is unhappy in its own way.", "Leo Tolstoy", "Anna Karenina"),
	("Memories warm you up from the inside. But they also tear you apart.", "Haruki Murakami", "Kafka on the Shore"),
	("It is nothing to die; it is dreadful not to live.", "Victor Hugo", "Les Misérables"),
	("Who controls the past controls the future. Who controls the present controls the past.", "George Orwell", "Nineteen Eighty-Four"),
	("Life is to be lived, not controlled; and humanity is won by continuing to play in face of certain defeat.", "Ralph Ellison", "Invisible Man"),
	("Last night I dreamt I went to Manderley again.", "Daphne du Maurier", "Rebecca"),
	("It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", "Jane Austen", "Pride and Prejudice"),
	("Tomorrow I’ll think of some way to get him back. After all, tomorrow is another day.", "Margaret Mitchell", "Gone with the Wind"),
	("Why, sometimes, I’ve believed as many as six impossible things before breakfast.", "Lewis Carroll", "Through the Looking-Glass"),
	("Don’t ever tell anybody anything. If you do, you start missing everybody.", "J. D. Salinger", "The Catcher in the Rye"),
	("It does not do to dwell on dreams and forget to live.", "J.K. Rowling", "Harry Potter and the Sorcerer’s Stone"),
	("You pierce my soul. I am half agony. Half hope. Tell me not that I am too late, that such precious feelings are gone for ever.", "Jane Austen", "Persuasion"),
	("So it goes…", "Kurt Vonnegut", "Slaughterhouse-Five"),
	("I had the epiphany that laughter was light, and light was laughter, and that this was the secret of the universe.", "Donna Tartt", "The Goldfinch"),
	("There are some things you learn best in calm, and some in storm.", "Willa Cather", "The Song of the Lark"),
	("When you play the game of thrones you win or you die.", "George R. R. Martin", "A Game of Thrones"),
	("The world breaks everyone, and afterward, many are strong at the broken places.", "Ernest Hemingway", "A Farewell to Arms"),
	("From that time on, the world was hers for the reading. She would never be lonely again, never miss the lack of intimate friends. Books became her friends and there was one for every mood.", "Betty Smith", "A Tree Grows in Brooklyn"),
	("Once upon a time there was a boy who loved a girl, and her laughter was a question he wanted to spend his whole life answering.", "Nicole Krauss", "The History of Love"),
	("Very few castaways can claim to have survived so long at sea as Mr. Patel, and none in the company of an adult Bengal tiger.", "Yann Martel", "Life of Pi"),
	("Anyone who ever gave you confidence, you owe them a lot.", "Truman Capote", "Breakfast at Tiffany’s"),
	("Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?", "L. M. Montgomery", "Anne of Green Gables"),
	("You forget what you want to remember, and you remember what you want to forget.", "Cormac McCarthy", "The Road"),
	("Call me Ishmael.", "Herman Melville", "Moby Dick"),
	("It was a pleasure to burn.", "Ray Bradbury", "Fahrenheit 451 "),
	("The past is not dead. In fact, it’s not even past.", "William Faulkner", "Requiem for a Nun"),
	("He has put a knife on the things that held us together and we have fallen apart.", "Chinua Achebe", "Things Fall Apart"),
	("Memories, even your most precious ones, fade surprisingly quickly. But I don’t go along with that. The memories I value most, I don’t ever see them fading.", "Kazuo Ishiguro", "Never Let Me Go"),
	("Nowadays people know the price of everything and the value of nothing.", "Oscar Wilde", "The Picture of Dorian Grey"),
	("Time is the longest distance between two places.", "Tennessee Williams", "The Glass Menagerie"),
	("The voice of the sea is seductive, never ceasing, whispering, clamoring, murmuring, inviting the soul to wander in abysses of solitude.", "Kate Chopin", "The Awakening"),
	("We dream in our waking moments, and walk in our sleep.", "Nathaniel Hawthorne", "The Scarlet Letter"),
	("The place where you made your stand never mattered. Only that you were there… and still on your feet.", "Stephen King", "The Stand"),
	("But soft! What light through yonder window breaks? It is the east, and Juliet is the sun.", "William Shakespeare", "Romeo and Juliet"),
	("My advice is, never do tomorrow what you can do today. Procrastination is the thief of time.", "Charles Dickens", "David Copperfield"),
	("So many things are possible just as long as you don’t know they’re impossible.", "Norton Juster", "The Phantom Tollbooth"),
	("I can’t stand it to think my life is going so fast and I’m not really living it.", "Ernest Hemingway", "The Sun Also Rises"),
	("Only the margin left to write on now. I love you, I love you, I love you.", "Dodie Smith", "I Capture the Castle"),
	("It doesn’t matter who you are or what you look like, so long as somebody loves you.", "Roald Dahl", "The Witches"),
	("The same substance composes us — the tree overhead, the stone beneath us, the bird, the beast, the star — we are all one, all moving to the same end.", "P.L. Travers", "Mary Poppins"),
	("I wish, as well as everybody else, to be perfectly happy; but, like everybody else, it must be in my own way.", "Jane Austen", "Sense and Sensibility"),
	("Love is holy because it is like grace – the worthiness of its object is never really what matters.", "Marilynne Robinson", "Gilead"),
	("Each time you happen to me all over again.", "Edith Wharton", "The Age of Innocence"),
	("Brave doesn’t mean you’re not scared. It means you go on even though you’re scared.", "Angie Thomas", "The Hate U Give"),
	("How easy it was to lie to strangers, to create with strangers the versions of our lives we imagined.", "Chimamanda Ngozi Adichie", "Americanah"),
	("And, when you want something, all the universe conspires in helping you to achieve it.", "Paulo Coelho", "The Alchemist"),
	("Life, with its rules, its obligations, and its freedoms, is like a sonnet: You’re given the form, but you have to write the sonnet yourself.", "Madeleine L’Engle", "A Wrinkle in Time"),
	("There is always something left to love.", "Gabriel García Márquez", "One Hundred Years of Solitude"),
	("The answer to the ultimate question of life, the universe and everything is 42.", "Douglas Adams", "The Hitchhiker’s Guide to the Galaxy"),
	("All the world’s a stage, and all the men and women merely players. They have their exits and their entrances; And one man in his time plays many parts.", "William Shakespeare", "As You Like It"),
	("Stay gold, Ponyboy, stay gold.", "S. E. Hinton", "The Outsiders"),
	("Sometimes I can hear my bones straining under the weight of all the lives I’m not living.", "Jonathan Safran Foer", "Extremely Loud and Incredibly Close"),
	("Do I love you? My God, if your love were a grain of sand, mine would be a universe of beaches.", "William Goldman", "The Princess Bride"),
	("Time moves slowly, but passes quickly.", "Alice Walker", "The Color Purple"),
	("You don’t know about me without you have read a book by the name of The Adventures of Tom Sawyer, but that ain’t no matter.", "Mark Twain", "The Adventures of Huckleberry Finn"),
	("Love is the longing for the half of ourselves we have lost.", "Milan Kundera", "The Unbearable Lightness of Being"),
	("It is our choices, Harry, that show what we truly are, far more than our abilities.", "J.K. Rowling", "Harry Potter and the Chamber of Secrets"),
	("For you, a thousand times over.", "Khaled Hosseini", "The Kite Runner"),
	("Then you must teach my daughter this same lesson. How to lose your innocence but not your hope. How to laugh forever.", "Amy Tan", "The Joy Luck Club"),
	("And may the odds be ever in your favor.", "Suzanne Collins", "The Hunger Games"),
	("Ralph wept for the end of innocence, the darkness of man’s heart, and the fall through the air of the true, wise friend called Piggy.", "William Golding", "Lord of the Flies"),
	("All human wisdom is summed up in these two words – ‘Wait and hope.’", "Alexandre Dumas", "The Count of Monte Cristo"),
	("Oh, the places you’ll go! You’ll be on your way up! You’ll be seeing great sights! You’ll join the high fliers who soar to high heights.", "Dr. Seuss", "Oh, the Places You’ll Go"),
	("The longer I live, the more uninformed I feel. Only the young have an explanation for everything.", "Isabel Allende", "City of the Beasts"),
	("Open your eyes and see what you can with them before they close forever.", "Anthony Doerr", "All the Light We Cannot See"),
	("If you have the guts to be yourself, other people’ll pay your price.", "John Updike", "Rabbit, Run"),
	("We were the people who were not in the papers. We lived in the blank white spaces at the edges of print. It gave us more freedom. We lived in the gaps between the stories.", "Margaret Atwood", "The Handmaid’s Tale"),
	("As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into an enormous insect.", "Franz Kafka", "The Metamorphosis"),
	("What does the brain matter compared with the heart?", "Virginia Woolf", "Mrs. Dalloway"),
	("We are such stuff as dreams are made on, and our little life is rounded with a sleep.", "William Shakespeare", "The Tempest"),
	("The creatures outside looked from pig to man, and from man to pig, and from pig to man again; but already it was impossible to say which was which.", "George Orwell", "Animal Farm"),
	("Most men and women will grow up to love their servitude and will never dream of revolution.", "Aldous Huxley", "Brave New World Revisited"),
	("There is no greater agony than bearing an untold story inside you.", "Maya Angelou", "I Know Why the Caged Bird Sings"),
	("As he read, I fell in love the way you fall asleep: slowly, and then all at once.", "John Green", "The Fault in Our Stars"),
	("Anything worth dying for is certainly worth living for.", "Joseph Heller", "Catch-22"),
	("All the world is made of faith, and trust, and pixie dust.", "J.M. Barrie", "Peter Pan"),
	("Get busy living or get busy dying.", "Stephen King", "Rita Hayworth and Shawshank Redemption"),
	("'But man is not made for defeat,’ he said. ‘A man can be destroyed but not defeated.’", "Ernest Hemingway", "The Old Man and the Sea"),
	("All we can know is that we know nothing. And that’s the height of human wisdom.", "Leo Tolstoy", "War and Peace"),
	("There is nothing like looking, if you want to find something. You certainly usually find something, if you look, but it is not always quite the something you were after.", "J.R.R. Tolkien", "The Hobbit"),
	("Life offers up these moments of joy despite everything.", "Sally Rooney", "Normal People"),
	("The world may be mean, but people don’t have to be, not if they refuse.", "Colson Whitehead", "The Underground Railroad"),
	("We had made a fetish out of our misfortune, fallen in love with it.", "Ann Patchett", "The Dutch House"),
	("Just like a murderer jumps out of nowhere in an alley, love jumped out in front of us and struck us both at once", "Mikhail Bulgakov", "The Master and Margarita"),
	("Life changes in the instant. The ordinary instant.", "Joan Didion", "The Year of Magical Thinking"),
	("I have a theory that selflessness and bravery aren’t all that different.",  "Veronica Roth", "Divergent"),
	("That’s the thing about books. They let you travel without moving your feet.", "Jhumpa Lahiri", "The Namesake"),
	("We don’t have time, Nephew, time has us. It holds us in its mouth like an owl holds a field mouse.", "Tommy Orange", "There There"),
	("I have been bent and broken, but - I hope - into a better shape.", "Charles Dickens", "Great Expectations"),
	("Though sympathy alone can’t alter facts, it can help to make them more bearable.", "Bram Stoker", "Dracula"),
	("There is nothing to writing. All you do is sit down at a typewriter and bleed.", "Ernest Hemingway", ""),
	("If there’s a book that you want to read, but it hasn’t been written yet, then you must write it.", "Toni Morrison", ""),
	("Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", "Virginia Woolf", "A Room of One’s Own"),
	("If you don’t have time to read, you don’t have the time (or the tools) to write. Simple as that.", "Stephen King", ""),
	("Substitute ‘damn’ every time you’re inclined to write ‘very;’ your editor will delete it and the writing will be just as it should be.", "Mark Twain", ""), 
	("No tears in the writer, no tears in the reader. No surprise in the writer, no surprise in the reader.", "Robert Frost", ""),
	("Read, read, read. Read everything — trash, classics, good and bad, and see how they do it. Just like a carpenter who works as an apprentice and studies the master. Read! You’ll absorb it. Then write. If it’s good, you’ll find out. If it’s not, throw it out of the window.", "William Faulkner", ""),
	("The difference between the almost right word and the right word is really a large matter. ’tis the difference between the lightning bug and the lightning.", "Mark Twain", ""),
	("You must stay drunk on writing so reality cannot destroy you.", "Ray Bradbury", ""),
	("Fiction is the truth inside the lie.", "Stephen King", ""),
	("Don’t tell me the moon is shining; show me the glint of light on broken glass.", "Anton Chekhov", ""),
	("How vain it is to sit down to write when you have not stood up to live.", "Henry David Thoreau", ""),
	("We have to continually be jumping off cliffs and developing our wings on the way down.", "Kurt Vonnegut", ""),
	("The first draft of anything is shit.", "Ernest Hemingway", ""),
	("A writer is someone for whom writing is more difficult than it is for other people.", "Thomas Mann", ""),
	("There are books of which the backs and covers are by far the best parts.", "Charles Dickens", ""),
	("let me live, love, and say it well in good sentences", "Sylvia Plath", ""),
	("Fill your paper with the breathings of your heart.", "William Wordsworth", ""),
	("Be yourself; everyone else is already taken.", "Oscar Wilde", ""),
	("Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.", "Bernard M. Baruch", ""),
	("You only live once, but if you do it right, once is enough.", "Mae West", ""),
	("If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "J.K. Rowling", "Harry Potter and the Goblet of Fire"),
	("Don’t walk in front of me… I may not follow. Don’t walk behind me… I may not lead. Walk beside me… just be my friend!", "Albert Camus", ""),
	("'Friendship ... is born at the moment when one man says to another.' 'What! You too? I thought that no one but myself . . .'", "C.S. Lewis", "The Four Loves"),
	("To live is the rarest thing in the world. Most people exist, that is all.", "Oscar Wilde", ""),
	("A friend is someone who knows all about you and still loves you.", "Elbert Hubbard", ""),
	("Always forgive your enemies; nothing annoys them so much.", "Oscar Wilde", ""),
	("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.", "H. Jackson Brown Jr.", "P.S. I Love You"),
	("Good friends, good books, and a sleepy conscience: this is the ideal life.", "Mark Twain", ""),
	("We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde", "Lady Windermere's Fan"),
	("It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.", "Maurice Switzer", "Mrs. Goose, Her Book"),
	("Life is what happens to us while we are making other plans.", "Allen Saunders", ""),
	("I solemnly swear that I am up to no good.", "J.K. Rowling", "Harry Potter and the Prisoner of Azkaban"),
	("I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.", "Dr. Seuss", ""),
	("A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.", "George R.R. Martin", "A Dance with Dragons"),
	("For every minute you are angry you lose sixty seconds of happiness.", "Ralph Waldo Emerson", ""),
	("I'm not upset that you lied to me, I'm upset that from now on I can't believe you.", "Friedrich Nietzsche", ""),
	("Everything you can imagine is real.", "Pablo Picasso", ""),
	("I have always imagined that Paradise will be a kind of library.", "Jorge Luis Borges", ""), 
	("We don't see things as they are, we see them as we are.", "Anaïs Nin", ""),
	("You can never get a cup of tea large enough or a book long enough to suit me.", "C.S. Lewis", ""), 
	("Life isn't about finding yourself. Life is about creating yourself.", "George Bernard Shaw", "")
]
